"""Models for the backend application."""
from datetime import datetime, timezone
from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, Text, Boolean, Float
from sqlalchemy.orm import relationship
from database import Base

db = Base()

# users, represents a local user of the application, the progress of the user is tracked in this database:


class User(Base):
    """Represents a user of the application."""
    __tablename__ = "users"  # actual table name in the database

    # unique identifier for each user
    id = Column(Integer, primary_key=True, index=True)
    # name shown in the app, defaults if not set
    display_name = Column(String, default="Learner")


# -------------------------------------------------
# domains, represents a domain of knowledge, such as "Mathematics" or "History", and contains a list of topics within that domain:

class Domain(Base):
    """Represents a domain of knowledge, such as "Mathematics" or "History", and contains a list of topics within that domain."""
    # NOTE: at the moment the only domain type is "language", but in the future we may add other types of domains, such as "roadrules" or "math"
    __tablename__ = "domains"

    # unique identifier for each domain
    id = Column(Integer, primary_key=True, index=True)
    # display name, e.g. "Spanish" — must be unique
    name = Column(String, unique=True, index=True)
    # category, e.g. "language", "roadrules"
    domain_type = Column(String)
    # AI instructions specific to this domain
    system_prompt = Column(Text)


# -------------------------------------------------
# vocabulary_items:

class VocabularyItem(Base):
    """Represents a vocabulary item within a specific domain, such as a word or phrase to learn."""
    __tablename__ = "vocabulary_items"

    # unique identifier
    id = Column(Integer, primary_key=True, index=True)
    # links this word to a specific domain
    domain_id = Column(Integer, ForeignKey("domains.id"))
    # the actual word/phrase to learn
    term = Column(String, index=True)
    # meaning of the term
    definition = Column(Text)
    # example usage in context
    example_sentence = Column(Text)
    # difficulty level, e.g. "A1", "B2"
    cefr_level = Column(String)

    # lets you access vocab_item.domain in Python (not a real column)
    domain = relationship("Domain")


# -------------------------------------------------
# grammar_rules:

class GrammarRule(Base):
    """Represents a grammar rule within a specific domain, such as a rule for verb conjugation or sentence structure."""
    __tablename__ = "grammar_rules"

    id = Column(Integer, primary_key=True, index=True)
    domain_id = Column(Integer, ForeignKey("domains.id"))
    # the name of the rule, e.g. "Present Perfect Tense"
    title = Column(String, index=True)
    # the actual teaching content explaining the rule
    explanation = Column(Text)
    # level of difficulty, e.g. "A1", "B2"
    cefr_level = Column(String)

    domain = relationship("Domain")


# -------------------------------------------------
# exercises:

class Exercise(Base):
    """Represents an exercise within a specific domain, which can be either a vocabulary or grammar exercise."""
    __tablename__ = "exercises"

    id = Column(Integer, primary_key=True, index=True)
    domain_id = Column(Integer, ForeignKey("domains.id"))
    # what kind of question it is e.g. "vocabulary", "grammar"
    type = Column(String)
    # links to a specific vocabulary item or grammar rule, depending on the type of exercise
    vocabulary_item_id = Column(Integer, ForeignKey(
        "vocabulary_items.id"), nullable=True)
    # links to a specific grammar rule, depending on the type of exercise
    grammar_rule_id = Column(Integer, ForeignKey(
        "grammar_rules.id"), nullable=True)
    # the actual question text shown to the user
    prompt = Column(Text)
    # the correct answer to the question
    correct_answer = Column(Text)
    # whether this exercise was generated by AI or manually created
    generated_by_ai = Column(Boolean, default=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))


# -------------------------------------------------
# user exercise attempts:

class UserExerciseAttempt(Base):
    """Represents an attempt by a user to answer an exercise, including the user's answer, whether it was correct, and any AI feedback."""
    __tablename__ = "user_exercise_attempts"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    exercise_id = Column(Integer, ForeignKey("exercises.id"))
    # what the user answered for this exercise attempt
    user_answer = Column(Text)
    # whether the user's answer was correct or not
    is_correct = Column(Boolean)
    # the ai's feedback on the user's answer, if any
    ai_feedback = Column(Text)
    attempted_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))


# -------------------------------------------------
# SRS = Spaced Repetition System.

class SrsCard(Base):
    """Represents a spaced repetition system (SRS) card for a specific user and vocabulary item, tracking the user's progress in learning that item."""
    __tablename__ = "srs_cards"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    vocabulary_item_id = Column(Integer, ForeignKey("vocabulary_items.id"))
    # a number that adjusts how quickly review gaps grow for this word, based on the user's performance (default is 2.5)
    ease_factor = Column(Float, default=2.5)
    # the number of days until the next review for this word (default is 1)
    interval_days = Column(Integer, default=1)
    # the number of times the user has successfully recalled this word (default is 0)
    repetitions = Column(Integer, default=0)
    # the date and time when the user should next review this word (default is now)
    due_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
